### ISSUE TITLE
Mobile view not responsive

### ISSUE THREAD

**Issue by adhamu** [phuoc-ng/1loc#495]
Looking at this on iOS 15.2 Safari on an iPhone 11 Pro, it doesn't render correctly at all. 

Screenshot:
![image](https://user-images.githubusercontent.com/4592613/147611790-0fcc7e92-c694-431a-9a4a-a42b4f706967.png)

**Comment by jacksonohallo** [comment]
can i work this "Mobile view not responsive"

**Comment by phuocng** [comment]
The website is responsive with the latest version.
