### ISSUE TITLE
Missing depth parameter to Array.prototype.flat method

### ISSUE THREAD

**Issue by fahimfaisaal** [phuoc-ng/1loc#508]
In the last `flat` [implementation](https://github.com/1milligram/1loc/blob/master/snippets/array/flatten-an-array.md), the `depth` parameter is missing. [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat)

**Comment by phuocng** [comment]
The `depth` parameter is optional.

**Comment by fahimfaisaal** [comment]
Then the function should be like this
```javascript
const flat = (arr, depth = 1) => arr.flat(depth);
```

**Comment by elkarouani** [comment]
I think that parameter depends on the use of the array, so it will be changeable not just constant to value 1 for global usage.
It will be an enhancement if the idea was global. In any case, it's an optional (not required) parameter for the method `Array.Prototype.flat()`.
