### ISSUE TITLE
[FEATURE] Pluralise based on length of array.

### ISSUE THREAD

**Issue by ghost** [phuoc-ng/1loc#528]
A simple line of code to pluralise a word based on the length of an array.

```
const pluralise = (items, singular, plural) => items.length > 1 || items.length === 0 ? plural : singular;
```

## Use Case

For if you have copy text that requires the interchangeability of pluralising based on the amount of items in an array.

```
let items = [0];
let string = `The ${pluralise(items, "test", "tests")}.`
console.log(string); // 'The item.'
items = [0, 1, 2, 3];
console.log(string); // 'The items'
```

**Comment by elkarouani** [comment]
Hi @mac-long, can you provide that snippet with use cases examples ?

**Comment by ghost** [comment]
@elkarouani I've added use case snippet

**Comment by elkarouani** [comment]
That's good @mac-long, can you also add the expected results of the console.log lines ?
There is a missing closing curly bracket in the second line

**Comment by ghost** [comment]
@elkarouani that should be closed now and I've added some comments which display the results

**Comment by elkarouani** [comment]
@mac-long, you can create a pull request to request adding this feature. Attention to the use case, I think you would repeat the second line after changing the items value
